/**
 * The committed dashboards and alert files, read at build time.
 *
 * `dashboards/` at the repository root is generated by `mikroscope dashboards
 * gen` and committed. Its panel titles, per-section counts and alert
 * thresholds are parsed from the files themselves, so a regeneration changes
 * the site in the same commit, and a section or rule the pages do not know
 * about fails the build instead of going unmentioned.
 *
 * Only structure is read — row titles, panel titles, the rule's uid, title,
 * summary, pending period, no-data state, severity, threshold and query —
 * never a panel's own query, which the pages do not reproduce.
 */
import { parse } from "yaml";
import influxJson from "../../../dashboards/mikroscope-influxdb.json?raw";
import promJson from "../../../dashboards/mikroscope-prometheus.json?raw";
import postgresJson from "../../../dashboards/mikroscope-postgres.json?raw";
import graphiteJson from "../../../dashboards/mikroscope-graphite.json?raw";
import elasticJson from "../../../dashboards/mikroscope-elasticsearch.json?raw";
import influxAlertsYaml from "../../../dashboards/mikroscope-alerts-influxdb.yaml?raw";
import promAlertsYaml from "../../../dashboards/mikroscope-alerts-prometheus.yaml?raw";
import postgresAlertsYaml from "../../../dashboards/mikroscope-alerts-postgres.yaml?raw";
import type { Lang } from "./measurements";

export type Store =
	"influxdb" | "prometheus" | "postgres" | "graphite" | "elasticsearch";

/** Every store a dashboard is generated for, in the order `gen` writes them. */
export const STORES: readonly Store[] = [
	"influxdb",
	"prometheus",
	"postgres",
	"graphite",
	"elasticsearch",
];

/**
 * The stores that also get an alert file. The rules are stated as SQL and
 * PromQL, and neither is Graphite's functions or Elasticsearch's aggregations,
 * so those two have dashboards and no alerts — which the pages say rather than
 * leaving a reader to find an absent file.
 */
export const ALERT_STORES: readonly Store[] = [
	"influxdb",
	"prometheus",
	"postgres",
];

/** How each store is named in prose. */
export const STORE_NAMES: Record<Store, string> = {
	influxdb: "InfluxDB 3",
	prometheus: "Prometheus",
	postgres: "PostgreSQL",
	graphite: "Graphite",
	elasticsearch: "Elasticsearch",
};

interface GrafanaPanel {
	type: string;
	title: string;
	panels?: GrafanaPanel[];
}

/**
 * The last row's title carries its own explanation after a dash ("Not
 * available on this device — measurements this kernel or board does not
 * produce (open to read why)"); the pages name the section by its first part.
 * "RouterOS API cross-checks — CPU and memory" also has a dash and is one
 * name, so only this one row is shortened.
 */
const NOT_AVAILABLE = "Not available on this device";
const sectionName = (rowTitle: string) =>
	rowTitle.startsWith(`${NOT_AVAILABLE} — `) ? NOT_AVAILABLE : rowTitle;

/** Row name → panel titles, in dashboard order. Panels above the first row belong to no section. */
function sectionsOf(raw: string): Map<string, string[]> {
	const { panels } = JSON.parse(raw) as { panels: GrafanaPanel[] };
	const out = new Map<string, string[]>();
	let current: string[] | null = null;
	for (const p of panels) {
		if (p.type === "row") {
			current = (p.panels ?? []).map((q) => q.title);
			out.set(sectionName(p.title), current);
		} else if (current === null) {
			throw new Error(
				`dashboards.ts: panel "${p.title}" sits above the first row`,
			);
		} else {
			// An open row (the Overview) keeps its panels at the top level, after it.
			current.push(p.title);
		}
	}
	return out;
}

const bySection: Record<Store, Map<string, string[]>> = {
	influxdb: sectionsOf(influxJson),
	prometheus: sectionsOf(promJson),
	postgres: sectionsOf(postgresJson),
	graphite: sectionsOf(graphiteJson),
	elasticsearch: sectionsOf(elasticJson),
};

/** Every section, in reading order: the InfluxDB file's order, with Prometheus-only rows after. */
export const sectionNames: readonly string[] = [
	...new Set([...bySection.influxdb.keys(), ...bySection.prometheus.keys()]),
];

export const isSection = (name: string) => sectionNames.includes(name);

export interface PanelEntry {
	title: string;
	/**
	 * The one of the two full dashboards carrying it, or null when both do.
	 * Never one of the other three: see the comment in panelsOf.
	 */
	only: "influxdb" | "prometheus" | null;
}

/**
 * One section's panels across both stores. A panel on one store only is placed
 * after the last panel both carry that precedes it on its own dashboard, which
 * reproduces the order either dashboard shows.
 */
export function panelsOf(section: string): {
	entries: PanelEntry[];
	stores: readonly ("influxdb" | "prometheus")[];
} {
	// The union is taken over the two full dashboards, and the "only on one
	// store" mark compares those two. The other three carry a subset by
	// construction — PostgreSQL where the SQL sink holds the measurement in
	// the same shape, Graphite and Elasticsearch where the panel states a
	// query for them — and marking every panel with the three of them would
	// bury the one distinction a reader of this list needs. The per-store
	// counts are the count table's job (DashboardCounts).
	const a = bySection.influxdb.get(section) ?? [];
	const b = bySection.prometheus.get(section) ?? [];
	const stores = (["influxdb", "prometheus"] as const).filter((s) =>
		bySection[s].has(section),
	);
	const merged: string[] = [];
	let ai = 0;
	for (const title of b) {
		const at = a.indexOf(title, ai);
		if (at === -1) {
			if (!merged.includes(title)) merged.push(title);
			continue;
		}
		for (const t of a.slice(ai, at + 1))
			if (!merged.includes(t)) merged.push(t);
		ai = at + 1;
	}
	for (const t of a.slice(ai)) if (!merged.includes(t)) merged.push(t);
	const entries = merged.map((title) => {
		const inA = a.includes(title);
		const inB = b.includes(title);
		return {
			title,
			only:
				inA && inB
					? null
					: inA
						? ("influxdb" as const)
						: ("prometheus" as const),
		};
	});
	return { entries, stores };
}

/** Panels in a section on one store, or null when that store ships no row for it. */
export const countOf = (store: Store, section: string): number | null =>
	bySection[store].get(section)?.length ?? null;

export const panelTotal = (store: Store): number =>
	[...bySection[store].values()].reduce((n, p) => n + p.length, 0);

/* ------------------------------------------------------------ alert rules */

interface RawRule {
	uid: string;
	title: string;
	for: string;
	noDataState: string;
	labels: { severity: string };
	annotations: { summary: string };
	data: {
		refId: string;
		model: {
			expr?: string;
			rawSql?: string;
			conditions?: { evaluator: { type: string; params: number[] } }[];
		};
	}[];
}

export interface AlertRule {
	uid: string;
	title: string;
	summary: string;
	for: string;
	noDataState: string;
	severity: string;
	/** The C step's evaluator: B compared with `value` by `op`. */
	op: ">" | "<";
	value: number;
	/** The A step's PromQL or SQL. */
	query: string;
}

const OPS = { gt: ">", lt: "<" } as const;

function rulesOf(raw: string, store: Store): AlertRule[] {
	const doc = parse(raw) as { groups: { rules: RawRule[] }[] };
	return doc.groups.flatMap((g) =>
		g.rules.map((r) => {
			const a = r.data.find((d) => d.refId === "A")?.model;
			const c = r.data.find((d) => d.refId === "C")?.model.conditions?.[0]
				?.evaluator;
			const query = store === "prometheus" ? a?.expr : a?.rawSql;
			if (
				query === undefined ||
				c === undefined ||
				!Object.hasOwn(OPS, c.type)
			) {
				throw new Error(
					`dashboards.ts: rule ${r.uid} in the ${store} file has no A query or no gt/lt threshold`,
				);
			}
			return {
				uid: r.uid,
				title: r.title,
				summary: r.annotations.summary,
				for: r.for,
				noDataState: r.noDataState,
				severity: r.labels.severity,
				op: OPS[c.type as keyof typeof OPS],
				value: c.params[0],
				query,
			};
		}),
	);
}

export const alertRules: Record<Store, AlertRule[]> = {
	influxdb: rulesOf(influxAlertsYaml, "influxdb"),
	prometheus: rulesOf(promAlertsYaml, "prometheus"),
	postgres: rulesOf(postgresAlertsYaml, "postgres"),
	// Neither store has an alert file; see ALERT_STORES above.
	graphite: [],
	elasticsearch: [],
};

/**
 * What each rule fires on, in words. This is the one authored part of the
 * alert table; a rule the files carry without an entry here, or an entry for a
 * rule no file carries, fails the build, so a new rule cannot ship unexplained.
 * The wording follows internal/dashboards/alerts.go and each rule's query.
 */
export const alertFiresWhen: Record<string, Record<Lang, string>> = {
	"mikroscope-agent-silent": {
		en: "fewer than 1 new sample reached the store in the last 2 minutes",
		es: "llegó al almacén menos de 1 muestra nueva en los últimos 2 minutos",
	},
	"mikroscope-egress-queue-drops": {
		en: "any port's own egress queue dropped a packet in every one of the last 10 minutes — sustained congestion, never a single burst",
		es: "la cola de salida de algún puerto descartó un paquete en cada uno de los últimos 10 minutos: congestión sostenida, nunca una ráfaga suelta",
	},
	"mikroscope-bridge-port-dark": {
		en: "a bridge port received packets while the bridge sent it neither a unicast nor a broadcast frame, for 10 minutes",
		es: "un puerto de bridge recibió paquetes mientras el bridge no le envió ni una trama unicast ni una broadcast, durante 10 minutos",
	},
	"mikroscope-port-errors": {
		en: "any port's MAC counted a typed error — overflow, FCS, collision — for 5 minutes running",
		es: "el MAC de algún puerto contó un error tipificado —desbordamiento, FCS, colisión— durante 5 minutos seguidos",
	},
	"mikroscope-softnet-drops": {
		en: "`softnet_stat` dropped a packet in the last 5 minutes",
		es: "`softnet_stat` descartó un paquete en los últimos 5 minutos",
	},
	"mikroscope-oom-kill": {
		en: "`/proc/vmstat` `oom_kill` moved in the last 5 minutes",
		es: "`oom_kill` de `/proc/vmstat` se movió en los últimos 5 minutos",
	},
	"mikroscope-detections": {
		en: "any detection in the last 5 minutes",
		es: "cualquier detección en los últimos 5 minutos",
	},
	"mikroscope-thermal-near-critical": {
		en: "a zone at or above 85 % of its own critical trip",
		es: "una zona al 85 % o más de su propio disparo crítico",
	},
	"mikroscope-conntrack-near-limit": {
		en: "`nf_conntrack` active objects above 0.8 of the kernel's limit",
		es: "objetos activos de `nf_conntrack` por encima de 0,8 del límite del kernel",
	},
	"mikroscope-ticks-slipped": {
		en: "the sampler slipped a tick in the last 5 minutes",
		es: "el muestreador perdió un tick por retraso en los últimos 5 minutos",
	},
	"mikroscope-agent-oom": {
		en: "the agent's own cgroup recorded an OOM kill in the last 5 minutes",
		es: "el propio cgroup del agente registró un OOM kill en los últimos 5 minutos",
	},
	"mikroscope-l2-loop": {
		en: "an own-address record on any port in the last 5 minutes",
		es: "un registro de own-address en cualquier puerto en los últimos 5 minutos",
	},
	"mikroscope-port-link-down": {
		en: "a link-down record on any port in the last 5 minutes",
		es: "un registro de link-down en cualquier puerto en los últimos 5 minutos",
	},
	"mikroscope-ecc-failure": {
		en: "the NAND reported an uncorrectable ECC failure in the last hour",
		es: "la NAND informó de un fallo ECC no corregible en la última hora",
	},
};

/**
 * Every rule uid, in the order the Prometheus file (the largest) lists them.
 * All three alert files are unioned, not two: a rule that only PostgreSQL
 * carried would otherwise be missing from the table that claims to list them
 * all.
 */
export const alertUids: readonly string[] = [
	...new Set(ALERT_STORES.flatMap((s) => alertRules[s]).map((r) => r.uid)),
];

for (const uid of alertUids) {
	if (!Object.hasOwn(alertFiresWhen, uid)) {
		throw new Error(
			`dashboards.ts: alert rule ${uid} has no alertFiresWhen entry`,
		);
	}
}
for (const uid of Object.keys(alertFiresWhen)) {
	if (!alertUids.includes(uid)) {
		throw new Error(
			`dashboards.ts: alertFiresWhen names ${uid}, which no alert file carries`,
		);
	}
}
