import { defineCollection } from "astro:content";
import { z } from "astro/zod";
import { docsLoader, i18nLoader } from "@astrojs/starlight/loaders";
import { docsSchema, i18nSchema } from "@astrojs/starlight/schema";

export const collections = {
	docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
	// Starlight's own UI strings, plus the handful this project adds. Extending
	// the schema rather than inventing a second dictionary keeps one lookup
	// (`Astro.locals.t`) for every string a component shows.
	i18n: defineCollection({
		loader: i18nLoader(),
		schema: i18nSchema({
			extend: z.object({
				"ms.theme.toDark": z.string().optional(),
				"ms.theme.toLight": z.string().optional(),
				"ms.provenance.measured": z.string().optional(),
				"ms.provenance.undated": z.string().optional(),
				"ms.runs.label": z.string().optional(),
				"ms.runs.rate": z.string().optional(),
				"ms.runs.floors": z.string().optional(),
				"ms.runs.cpu": z.string().optional(),
				"ms.runs.usPerSample": z.string().optional(),
				"ms.runs.rss": z.string().optional(),
				"ms.runs.slipped": z.string().optional(),
				"ms.runs.gapsDrops": z.string().optional(),
				"ms.runs.default": z.string().optional(),
				"ms.scroll.hint": z.string().optional(),
				"ms.claim.notMeasured": z.string().optional(),
				"ms.claim.untested": z.string().optional(),
				"ms.claim.notProvoked": z.string().optional(),
				"ms.claim.deviceSpecific": z.string().optional(),
				"ms.writes.title.install": z.string().optional(),
				"ms.writes.title.expose": z.string().optional(),
				"ms.writes.title.upgrade": z.string().optional(),
				"ms.writes.title.uninstall": z.string().optional(),
				"ms.writes.tag": z.string().optional(),
				"ms.writes.plan": z.string().optional(),
				"ms.writes.verify": z.string().optional(),
				"ms.seeAlso.label": z.string().optional(),
				"ms.fault.real": z.string().optional(),
				"ms.fault.provoked": z.string().optional(),
				"ms.fault.unprovoked": z.string().optional(),
				"ms.privileged.badge": z.string().optional(),
				"ms.envlist.label": z.string().optional(),
				"ms.envlist.key": z.string().optional(),
				"ms.envlist.written": z.string().optional(),
				"ms.envlist.from": z.string().optional(),
				"ms.envlist.holds": z.string().optional(),
				"ms.envlist.always": z.string().optional(),
				"ms.envlist.aboveZero": z.string().optional(),
				"ms.envlist.whenSet": z.string().optional(),
				"ms.envlist.default": z.string().optional(),
				"ms.doctor.label": z.string().optional(),
				"ms.doctor.check": z.string().optional(),
				"ms.doctor.passes": z.string().optional(),
				"ms.doctor.fix": z.string().optional(),
				"ms.cadence.label": z.string().optional(),
				"ms.cadence.meaning": z.string().optional(),
				"ms.dash.countsLabel": z.string().optional(),
				"ms.dash.section": z.string().optional(),
				"ms.dash.total": z.string().optional(),
				"ms.dash.noRow": z.string().optional(),
				"ms.dash.influxOnly": z.string().optional(),
				"ms.dash.promOnly": z.string().optional(),
				"ms.alerts.label": z.string().optional(),
				"ms.alerts.rule": z.string().optional(),
				"ms.alerts.firesWhen": z.string().optional(),
				"ms.alerts.threshold": z.string().optional(),
				"ms.alerts.severity": z.string().optional(),
				"ms.alerts.for": z.string().optional(),
				"ms.alerts.noData": z.string().optional(),
				"ms.alerts.stores": z.string().optional(),
				"ms.alerts.both": z.string().optional(),
				"ms.alerts.all": z.string().optional(),
				"ms.breadcrumb.home": z.string().optional(),
			}),
		}),
	}),
};
