//go:build linux

package lab

import (
	"bytes"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/binary"
	"encoding/pem"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestRandomStringIsAlphanumericAndUsesTheWholeAlphabet(t *testing.T) {
	s, err := randomString(rand.Reader, 4000)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Trim(s, alnum) != "" {
		t.Errorf("a character outside [A-Za-z0-9]: %q", strings.Trim(s, alnum))
	}
	for _, c := range alnum {
		if !strings.ContainsRune(s, c) {
			t.Errorf("4000 draws never gave %q", c)
		}
	}
	if _, err = randomString(bytes.NewReader(nil), 3); err == nil {
		t.Error("an empty source did not fail")
	}
}

func TestEnvFileRoundTrip(t *testing.T) {
	b, err := NewEnvFile(rand.Reader, time.Date(2026, 9, 26, 23, 0, 0, 0, time.UTC))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(b), "# The virtual RouterOS lab's credentials, generated by mikroscope-lab on 2026-09-26.\n") {
		t.Errorf("header: %q", b)
	}
	c, err := ParseEnvFile(b)
	if err != nil {
		t.Fatal(err)
	}
	if c.User != "admin" || len(c.Password) != 24 || len(c.Token) != 32 || c.Password == c.Token[:24] {
		t.Errorf("parsed %q %d %d", c.User, len(c.Password), len(c.Token))
	}
	if _, err = NewEnvFile(bytes.NewReader(make([]byte, 10)), time.Now()); err == nil {
		t.Error("a short random source did not fail")
	}
}

// What the shell that sourced .env for lab.sh took, and what it did not.
func TestParseEnvFileAsTheShellReadIt(t *testing.T) {
	c, err := ParseEnvFile([]byte("# c\n\nexport LAB_ADMIN_USER=admin\nLAB_ADMIN_PASSWORD='pw1'\nLAB_AGENT_TOKEN=\"tok\"\nnonsense\nOTHER=x\n"))
	if err != nil || c.User != "admin" || c.Password != "pw1" || c.Token != "tok" {
		t.Errorf("ParseEnvFile = %+v, %v", c, err)
	}
	// A password or a token of anything but letters and digits is refused,
	// by its name and without its value: each would reach a RouterOS script,
	// a URL or a command line that would need it quoted.
	for _, env := range []string{
		"LAB_ADMIN_PASSWORD='p w'\nLAB_AGENT_TOKEN=tok\n",
		"LAB_ADMIN_PASSWORD=p$w\nLAB_AGENT_TOKEN=tok\n",
		"LAB_ADMIN_PASSWORD=p\"w\nLAB_AGENT_TOKEN=tok\n",
		"LAB_ADMIN_PASSWORD=pw\nLAB_AGENT_TOKEN=t;k\n",
		"LAB_ADMIN_PASSWORD=pw\nLAB_AGENT_TOKEN=tök\n",
	} {
		_, err = ParseEnvFile([]byte(env))
		name := "LAB_ADMIN_PASSWORD"
		if strings.Contains(env, "pw\n") {
			name = "LAB_AGENT_TOKEN"
		}
		if err == nil || !strings.HasPrefix(err.Error(), name+" holds a character") || strings.ContainsAny(err.Error(), "$\";ö") {
			t.Errorf("%q: %v", env, err)
		}
	}
	if _, err = ParseEnvFile([]byte("LAB_ADMIN_PASSWORD=x\n")); err == nil {
		t.Error("an .env without a token parsed")
	}
	if _, err = ParseEnvFile([]byte(strings.Repeat("x", 70000))); err == nil {
		t.Error("a line past the scanner's limit parsed")
	}
}

func TestLoadEnvWritesOnce0600AndSaysNothingOfTheSecrets(t *testing.T) {
	r := newRig(t)
	r.mustMain("env")
	if _, err := os.Stat(filepath.Join(r.state, ".env")); !errors.Is(err, os.ErrNotExist) {
		t.Error("env wrote the credentials; it only says where they are")
	}
	cfg, _ := Load(func(n string) string {
		if n == "LAB_STATE_DIR" {
			return r.state
		}
		return ""
	}, r.labDir, r.repo, r.repo)
	l := New(cfg, r.options())
	c, err := l.loadEnv()
	if err != nil {
		t.Fatal(err)
	}
	st, err := os.Stat(cfg.EnvFile)
	if err != nil || st.Mode().Perm() != 0o600 {
		t.Fatalf("mode %v, %v", st.Mode().Perm(), err)
	}
	if strings.Contains(r.stderr.String(), c.Password) || strings.Contains(r.stderr.String(), c.Token) ||
		!strings.Contains(r.stderr.String(), "wrote "+cfg.EnvFile+" (admin password and agent token; mode 0600)") {
		t.Errorf("stderr: %s", r.stderr.String())
	}
	// A second lab reads the same file and writes nothing.
	again, err := New(cfg, r.options()).loadEnv()
	if err != nil || *again != *c {
		t.Errorf("a second read: %+v %v", again, err)
	}
	if err = os.WriteFile(cfg.EnvFile, []byte("broken\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err = New(cfg, r.options()).loadEnv(); err == nil {
		t.Error("a broken .env loaded")
	}
	if err = writeExclusive(cfg.EnvFile, []byte("x"), 0o600); !errors.Is(err, os.ErrExist) {
		t.Errorf("writeExclusive over a file: %v", err)
	}
	cfg.EnvFile = filepath.Join(t.TempDir(), "no", "dir", ".env")
	if _, err = New(cfg, r.options()).loadEnv(); err == nil {
		t.Error("an .env that cannot be written loaded")
	}
}

// NewSSHKey writes OpenSSH's own format: parse it back field by field, and
// have ssh-keygen derive the public key from it when it is installed.
func TestNewSSHKeyIsOpenSSHFormat(t *testing.T) {
	priv, pub, err := NewSSHKey(rand.Reader, "mikroscope-lab")
	if err != nil {
		t.Fatal(err)
	}
	f := strings.Fields(string(pub))
	if len(f) != 3 || f[0] != "ssh-ed25519" || f[2] != "mikroscope-lab" || !strings.HasSuffix(string(pub), "\n") {
		t.Fatalf("public key %q", pub)
	}
	wirePub, err := base64.StdEncoding.DecodeString(f[1])
	if err != nil {
		t.Fatal(err)
	}
	pubKey, privKey := parseOpenSSHKey(t, priv, wirePub)
	msg := []byte("lab")
	if !ed25519.Verify(pubKey, msg, ed25519.Sign(privKey, msg)) {
		t.Fatal("the pair does not sign and verify")
	}
	keygenAgrees(t, priv, f[1])
}

// parseOpenSSHKey reads PROTOCOL.key's unencrypted format field by field and
// returns the key pair it holds.
func parseOpenSSHKey(t *testing.T, priv, wirePub []byte) (ed25519.PublicKey, ed25519.PrivateKey) {
	t.Helper()
	block, rest := pem.Decode(priv)
	if block == nil || block.Type != "OPENSSH PRIVATE KEY" || len(rest) != 0 {
		t.Fatalf("private key %q", priv)
	}
	rd := &wire{b: block.Bytes}
	if magic := rd.bytes(15); string(magic) != "openssh-key-v1\x00" {
		t.Fatalf("magic %q", magic)
	}
	cipher, kdf, options, count := rd.str(), rd.str(), rd.str(), rd.u32()
	if cipher != "none" || kdf != "none" || options != "" || count != 1 {
		t.Fatalf("cipher %q, kdf %q, options %q, count %d", cipher, kdf, options, count)
	}
	if got := rd.raw(); !bytes.Equal(got, wirePub) {
		t.Fatal("the public key block differs from the .pub")
	}
	inner := &wire{b: rd.raw()}
	if len(inner.b)%8 != 0 || rd.left() != 0 {
		t.Fatalf("inner block of %d bytes, %d left over", len(inner.b), rd.left())
	}
	if check1, check2 := inner.u32(), inner.u32(); check1 != check2 {
		t.Fatal("the check integers differ")
	}
	if inner.str() != "ssh-ed25519" {
		t.Fatal("key type")
	}
	pubKey, privKey := inner.raw(), inner.raw()
	if len(pubKey) != ed25519.PublicKeySize || len(privKey) != ed25519.PrivateKeySize ||
		!bytes.Equal(ed25519.PrivateKey(privKey).Public().(ed25519.PublicKey), pubKey) {
		t.Fatal("the private key does not hold the public one")
	}
	if inner.str() != "mikroscope-lab" {
		t.Fatal("comment")
	}
	for i := byte(1); inner.left() > 0; i++ {
		if p := inner.bytes(1)[0]; p != i {
			t.Fatalf("padding byte %d is %d", i, p)
		}
	}
	return pubKey, privKey
}

// keygenAgrees has ssh-keygen derive the public key from the private one,
// when ssh-keygen is installed.
func keygenAgrees(t *testing.T, priv []byte, pubBase64 string) {
	t.Helper()
	keygen, lookErr := exec.LookPath("ssh-keygen")
	if lookErr != nil {
		t.Log("ssh-keygen is not installed: the format was checked field by field only")
		return
	}
	key := filepath.Join(t.TempDir(), "id_ed25519")
	if err := os.WriteFile(key, priv, 0o600); err != nil {
		t.Fatal(err)
	}
	out, err := exec.CommandContext(t.Context(), keygen, "-y", "-f", key).Output() // #nosec G204 -- ssh-keygen on the test's own key
	if err != nil {
		t.Fatalf("ssh-keygen -y: %v", err)
	}
	if got := strings.Fields(string(out)); len(got) < 2 || got[1] != pubBase64 {
		t.Errorf("ssh-keygen derived %q from the private key, the .pub has %q", out, pubBase64)
	}
}

type wire struct{ b []byte }

func (w *wire) left() int { return len(w.b) }
func (w *wire) bytes(n int) []byte {
	out := w.b[:n]
	w.b = w.b[n:]
	return out
}
func (w *wire) u32() uint32 { return binary.BigEndian.Uint32(w.bytes(4)) }
func (w *wire) raw() []byte { return w.bytes(int(w.u32())) }
func (w *wire) str() string { return string(w.raw()) }

func TestNewSSHKeyNeedsRandomness(t *testing.T) {
	if _, _, err := NewSSHKey(bytes.NewReader(make([]byte, 10)), "x"); err == nil {
		t.Error("10 random bytes made a key")
	}
	if _, _, err := NewSSHKey(bytes.NewReader(make([]byte, 33)), "x"); err == nil {
		t.Error("no bytes left for the check integer, and still a key")
	}
}

func TestEnsureKeyMakesItOnce(t *testing.T) {
	r := newRig(t)
	cfg, _ := Load(func(n string) string {
		if n == "LAB_STATE_DIR" {
			return r.state
		}
		return ""
	}, r.labDir, r.repo, r.repo)
	l := New(cfg, r.options())
	if err := l.ensureKey(); err != nil {
		t.Fatal(err)
	}
	for name, mode := range map[string]os.FileMode{"": 0o700, "id_ed25519": 0o600, "id_ed25519.pub": 0o644} {
		st, err := os.Stat(filepath.Join(cfg.SSHDir, name))
		if err != nil || st.Mode().Perm() != mode {
			t.Errorf("%s: %v %v", name, st.Mode().Perm(), err)
		}
	}
	first, _ := os.ReadFile(filepath.Join(cfg.SSHDir, "id_ed25519")) // #nosec G304 -- the test's own key
	if err := l.ensureKey(); err != nil {
		t.Fatal(err)
	}
	if again, _ := os.ReadFile(filepath.Join(cfg.SSHDir, "id_ed25519")); !bytes.Equal(first, again) { // #nosec G304 -- the test's own key
		t.Error("a second ensureKey replaced the key")
	}
	cfg.SSHDir = filepath.Join(cfg.EnvFile, "under-a-file")
	if err := os.WriteFile(cfg.EnvFile, nil, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := New(cfg, r.options()).ensureKey(); err == nil {
		t.Error("a key under a file was made")
	}
}
