//go:build linux

package lab

import (
	"bufio"
	"bytes"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/binary"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"time"
)

// Credentials are the lab router's: the admin password (WebFig, the API, a
// password login) and a bearer token for `install --expose` tests. They live
// in <state>/.env, mode 0600 and gitignored, generated on first use and
// never printed: `env` says where they are, not what is in them. The
// password reaches the router in a file over scp, and the token reaches the
// CLI through its container's environment; neither is ever an argument of a
// command, where the host's process table would show it.
type Credentials struct {
	User     string
	Password string
	Token    string
}

const alnum = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

// randomString is n characters drawn uniformly from [A-Za-z0-9], as lab.sh's
// `tr -dc 'A-Za-z0-9' </dev/urandom | head -c n` drew them.
func randomString(r io.Reader, n int) (string, error) {
	b := make([]byte, n)
	limit := big.NewInt(int64(len(alnum)))
	for i := range b {
		v, err := rand.Int(r, limit)
		if err != nil {
			return "", err
		}
		b[i] = alnum[v.Int64()]
	}
	return string(b), nil
}

// NewEnvFile is a fresh .env: an admin password of 24 characters and an
// agent token of 32.
func NewEnvFile(r io.Reader, day time.Time) ([]byte, error) {
	pw, err := randomString(r, 24)
	if err != nil {
		return nil, err
	}
	tok, err := randomString(r, 32)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "# The virtual RouterOS lab's credentials, generated by mikroscope-lab on %s.\n", day.UTC().Format("2006-01-02"))
	b.WriteString("# Gitignored. The lab router is reachable only from this machine's loopback.\n")
	b.WriteString("LAB_ADMIN_USER=admin\n")
	b.WriteString("LAB_ADMIN_PASSWORD=" + pw + "\n")
	b.WriteString("LAB_AGENT_TOKEN=" + tok + "\n")
	return b.Bytes(), nil
}

// ParseEnvFile reads KEY=VALUE lines. Comments, blank lines and anything
// that is not an assignment are skipped; a value in matching single or
// double quotes loses them, as the shell that sourced the file for lab.sh
// took them off.
func ParseEnvFile(b []byte) (Credentials, error) {
	var c Credentials
	sc := bufio.NewScanner(bytes.NewReader(b))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		name, value, ok := strings.Cut(strings.TrimPrefix(line, "export "), "=")
		if !ok {
			continue
		}
		if len(value) >= 2 && (value[0] == '"' || value[0] == '\'') && value[len(value)-1] == value[0] {
			value = value[1 : len(value)-1]
		}
		switch strings.TrimSpace(name) {
		case "LAB_ADMIN_USER":
			c.User = value
		case "LAB_ADMIN_PASSWORD":
			c.Password = value
		case "LAB_AGENT_TOKEN":
			c.Token = value
		}
	}
	if err := sc.Err(); err != nil {
		return c, err
	}
	if c.Password == "" || c.Token == "" {
		return c, errors.New("no LAB_ADMIN_PASSWORD or no LAB_AGENT_TOKEN")
	}
	// Letters and digits, as the lab writes them: the password goes into a
	// RouterOS script and the tests' URLs, and the token into a container's
	// environment and --token, where anything else would need quoting each
	// place differently. The message names the variable, never the value.
	for name, v := range map[string]string{"LAB_ADMIN_PASSWORD": c.Password, "LAB_AGENT_TOKEN": c.Token} {
		if strings.Trim(v, alnum) != "" {
			return c, fmt.Errorf("%s holds a character that is not a letter or a digit: remove the .env and the lab writes a new one", name)
		}
	}
	return c, nil
}

// loadEnv reads the lab's .env, writing a new one first when there is none.
// The file is created mode 0600 and never overwritten: O_EXCL, so two runs
// that race to create it cannot both write one.
func (l *Lab) loadEnv() (*Credentials, error) {
	if l.creds != nil {
		return l.creds, nil
	}
	b, err := os.ReadFile(l.cfg.EnvFile)
	if errors.Is(err, os.ErrNotExist) {
		b, err = l.writeEnv()
	}
	if err != nil {
		return nil, err
	}
	c, err := ParseEnvFile(b)
	if err != nil {
		return nil, die("%s: %v", l.cfg.EnvFile, err)
	}
	l.creds = &c
	return l.creds, nil
}

// writeEnv writes a new .env and returns it, or, when another run wrote one
// first, returns that one.
func (l *Lab) writeEnv() ([]byte, error) {
	b, err := NewEnvFile(rand.Reader, l.now())
	if err != nil {
		return nil, err
	}
	err = writeExclusive(l.cfg.EnvFile, b, 0o600)
	switch {
	case errors.Is(err, os.ErrExist):
		return os.ReadFile(l.cfg.EnvFile)
	case err != nil:
		return nil, err
	}
	l.sayf("wrote %s (admin password and agent token; mode 0600)", l.cfg.EnvFile)
	return b, nil
}

// writeExclusive creates path with data and perm, and fails if it exists.
func writeExclusive(path string, data []byte, perm os.FileMode) error {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, perm) // #nosec G304 -- the lab's own state
	if err != nil {
		return err
	}
	if _, err = f.Write(data); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}

// ─── The lab's ssh key ─────────────────────────────────────────────────────

// NewSSHKey is an ed25519 key pair in OpenSSH's formats: the private key as
// an unencrypted "OPENSSH PRIVATE KEY" (PROTOCOL.key) and the public key as
// an authorized_keys line with the comment.
func NewSSHKey(r io.Reader, comment string) (private, public []byte, err error) {
	pub, priv, err := ed25519.GenerateKey(r)
	if err != nil {
		return nil, nil, err
	}
	wirePub := sshString(nil, []byte("ssh-ed25519"))
	wirePub = sshString(wirePub, pub)

	var check [4]byte
	if _, err = io.ReadFull(r, check[:]); err != nil {
		return nil, nil, err
	}
	inner := append([]byte(nil), check[:]...)
	inner = append(inner, check[:]...)
	inner = sshString(inner, []byte("ssh-ed25519"))
	inner = sshString(inner, pub)
	inner = sshString(inner, priv) // the seed, then the public key: 64 bytes
	inner = sshString(inner, []byte(comment))
	for i := byte(1); len(inner)%8 != 0; i++ {
		inner = append(inner, i)
	}

	body := append([]byte("openssh-key-v1"), 0)
	body = sshString(body, []byte("none"))
	body = sshString(body, []byte("none"))
	body = sshString(body, nil)
	body = binary.BigEndian.AppendUint32(body, 1)
	body = sshString(body, wirePub)
	body = sshString(body, inner)

	private = pem.EncodeToMemory(&pem.Block{Type: "OPENSSH PRIVATE KEY", Bytes: body})
	public = []byte("ssh-ed25519 " + base64.StdEncoding.EncodeToString(wirePub) + " " + comment + "\n")
	return private, public, nil
}

// sshString appends s as the SSH wire format's string: a 32-bit length and
// the bytes.
func sshString(b, s []byte) []byte {
	b = binary.BigEndian.AppendUint32(b, uint32(len(s))) // #nosec G115 -- key material, far below 4 GiB
	return append(b, s...)
}

// ensureKey makes the lab's ssh key when there is none: .cache/ssh, mode
// 0700, with id_ed25519 (0600) and id_ed25519.pub. The pair is written into
// a directory of its own and renamed into place whole, so two first runs
// of the two architectures, which share .cache/ssh under different locks,
// can never leave one run's private key beside the other's public key:
// the second rename fails on the first one's directory, and the second run
// uses that pair.
func (l *Lab) ensureKey() error {
	key := filepath.Join(l.cfg.SSHDir, "id_ed25519")
	if _, err := os.Stat(key); err == nil {
		return nil
	}
	if err := os.MkdirAll(l.cfg.Cache, 0o750); err != nil {
		return fmt.Errorf("making the lab's ssh key: %w", err)
	}
	tmp, err := os.MkdirTemp(l.cfg.Cache, ".ssh-")
	if err != nil {
		return fmt.Errorf("making the lab's ssh key: %w", err)
	}
	defer os.RemoveAll(tmp)
	if err = os.Chmod(tmp, 0o700); err != nil { // #nosec G302 -- a directory, which needs its x bit
		return fmt.Errorf("making the lab's ssh key: %w", err)
	}
	priv, pub, err := NewSSHKey(rand.Reader, "mikroscope-lab")
	if err != nil {
		return fmt.Errorf("making the lab's ssh key: %w", err)
	}
	if err = writeExclusive(filepath.Join(tmp, "id_ed25519"), priv, 0o600); err != nil {
		return fmt.Errorf("making the lab's ssh key: %w", err)
	}
	if err = writeExclusive(filepath.Join(tmp, "id_ed25519.pub"), pub, 0o644); err != nil {
		return fmt.Errorf("making the lab's ssh key: %w", err)
	}
	// rename(2) replaces an empty directory (one Docker made for a mount)
	// and fails on one with files in it. os.Rename refuses any directory
	// in the new name's place, so the system call is made directly.
	if err = syscall.Rename(tmp, l.cfg.SSHDir); err != nil {
		if _, statErr := os.Stat(key); statErr == nil {
			return nil
		}
		return fmt.Errorf("making the lab's ssh key: %s has no id_ed25519 and cannot be replaced: %w", l.cfg.SSHDir, err)
	}
	l.sayf("generated the lab's ssh key in %s", l.cfg.SSHDir)
	return nil
}
