#!/usr/bin/env bash
# lab.sh — the virtual RouterOS lab: MikroTik's Cloud Hosted Router under QEMU
# in a Docker container, provisioned once into a clean snapshot (container
# package installed, device-mode container=yes confirmed) and reset to it in
# seconds. Every RouterOS test mikroscope runs goes here, never to a real
# router. The README next to this file says what it is, what it needs, what
# each step took and where it stops being a router.
#
#   lab.sh up | down | reset | status | provision | fetch | image
#   lab.sh residue              what an install could have left on the router
#   lab.sh ssh [command]        the router's console, or one command
#   lab.sh cli <verb> [flags]   the mikroscope CLI, from the lab's LAN side
#   lab.sh put <file> [name]    upload a file to the router
#   lab.sh import <file.rsc>    upload a RouterOS script, /import it, delete it
#   lab.sh console              the serial console (Ctrl-] to leave)
#   lab.sh power-cycle          pull the power and put it back
#
# Settings, from the environment (the Makefile passes them through):
#   LAB_ARCH   x86_64 (default; KVM) or arm64 (UEFI, TCG on an x86 host)
#   LAB_ROS    RouterOS version, default 7.24.4
#   LAB_MEM, LAB_CPUS, LAB_DISK_SIZE   the VM: 1024 MiB, 2 vCPU, 1G disk
#   LAB_AGENT_ROUTES, LAB_AGENT_TARGET   see below; 172.30.0.0/16, 172.30.10.2:9123
#   MIKROSCOPE_BIN   the CLI `lab.sh cli` runs, default the one on PATH
set -euo pipefail

LAB_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
LAB_ARCH=${LAB_ARCH:-x86_64}
LAB_ROS=${LAB_ROS:-7.24.4}
LAB_MEM=${LAB_MEM:-1024}
LAB_CPUS=${LAB_CPUS:-2}
LAB_DISK_SIZE=${LAB_DISK_SIZE:-1G}
LAB_IMAGE=${LAB_IMAGE:-mikroscope-lab:local}
LAB_DL=${LAB_DL:-https://download.mikrotik.com/routeros}
# What the lab's namespace routes to the router, and what the host's agent
# port forwards to. Both take effect when the container is created (up after
# down, or reset). A --subnet outside the routes would leave the namespace by
# its default route, towards the host's own gateway: widen the routes first.
LAB_AGENT_ROUTES=${LAB_AGENT_ROUTES:-172.30.0.0/16}
LAB_AGENT_TARGET=${LAB_AGENT_TARGET:-172.30.10.2:9123}

case "$LAB_ARCH" in
x86_64)
	short=x86
	img_zip="chr-$LAB_ROS.img.zip"
	pkg_zip="all_packages-x86-$LAB_ROS.zip"
	port_suffix=1
	;;
arm64)
	short=arm64
	img_zip="chr-$LAB_ROS-arm64.img.zip"
	pkg_zip="all_packages-arm64-$LAB_ROS.zip"
	port_suffix=2
	;;
*)
	echo "lab: LAB_ARCH must be x86_64 or arm64, got $LAB_ARCH" >&2
	exit 2
	;;
esac

NAME=${LAB_NAME:-mikroscope-lab-$short}
CACHE=$LAB_DIR/.cache
DL=$CACHE/downloads/$LAB_ROS
VM=$CACHE/vm/$LAB_ARCH-$LAB_ROS
SSHD=$CACHE/ssh
ENV_FILE=$LAB_DIR/.env

# Host ports, on 127.0.0.1 only: 220N ssh, 800N WebFig, 870N API, 910N agent,
# with N = 1 for x86_64 and 2 for arm64, so both labs can run side by side.
P_SSH=220$port_suffix
P_HTTP=800$port_suffix
P_API=870$port_suffix
P_AGENT=910$port_suffix

T0=$(date +%s)
say() { printf '[lab %s +%4ss] %s\n' "$LAB_ARCH" "$(($(date +%s) - T0))" "$*" >&2; }
die() {
	say "error: $*"
	exit 1
}

# ─── Credentials ─────────────────────────────────────────────────────────────

# .env holds the router's admin password (WebFig, the API, a password login)
# and a bearer token for `install --expose` tests. Generated on first use and
# never printed: `lab.sh env` shows where it is, not what is in it.
load_env() {
	if [ ! -f "$ENV_FILE" ]; then
		umask 077
		{
			echo "# The virtual RouterOS lab's credentials, generated by lab.sh on $(date -u +%Y-%m-%d)."
			echo "# Gitignored. The lab router is reachable only from this machine's loopback."
			echo "LAB_ADMIN_USER=admin"
			echo "LAB_ADMIN_PASSWORD=$(rand 24)"
			echo "LAB_AGENT_TOKEN=$(rand 32)"
		} >"$ENV_FILE"
		say "wrote $ENV_FILE (admin password and agent token; mode 0600)"
	fi
	# shellcheck disable=SC1090
	. "$ENV_FILE"
}

rand() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$1"; }

ensure_key() {
	if [ ! -f "$SSHD/id_ed25519" ]; then
		mkdir -p "$SSHD"
		chmod 700 "$SSHD"
		# ssh-keygen wants a passwd entry for its uid, so it runs as root and
		# hands the key to whoever runs lab.sh.
		docker run --rm --entrypoint sh -v "$SSHD:/out" "$LAB_IMAGE" -c \
			"ssh-keygen -q -t ed25519 -N '' -C mikroscope-lab -f /out/id_ed25519 && chown $(id -u):$(id -g) /out/id_ed25519 /out/id_ed25519.pub"
		say "generated the lab's ssh key in $SSHD"
	fi
}

# ─── Image, downloads, disk ──────────────────────────────────────────────────

cmd_image() {
	say "building $LAB_IMAGE"
	docker build -q -t "$LAB_IMAGE" "$LAB_DIR" >/dev/null
}

ensure_image() {
	docker image inspect "$LAB_IMAGE" >/dev/null 2>&1 || cmd_image
}

# tool runs one command in a throwaway container with the cache mounted, as
# the user running lab.sh, so what it writes under .cache is theirs to delete.
tool() {
	docker run --rm --user "$(id -u):$(id -g)" -v "$CACHE:/cache" -w /cache --entrypoint bash "$LAB_IMAGE" -c "$1"
}

# fetch downloads from MikroTik and checks each file against the .sha256 that
# MikroTik publishes beside it on download.mikrotik.com. Both come from the
# same server over HTTPS, so the check catches a damaged or truncated
# download, not a compromised origin; RouterOS itself verifies the signature
# of every .npk it installs.
cmd_fetch() {
	ensure_image
	mkdir -p "$DL"
	local f
	for f in "$img_zip" "$pkg_zip"; do
		if [ -f "$DL/$f" ] && [ -f "$DL/$f.sha256" ]; then
			continue
		fi
		say "downloading $LAB_DL/$LAB_ROS/$f"
		tool "set -e; cd downloads/$LAB_ROS
			curl -fsSL -o '$f.part' '$LAB_DL/$LAB_ROS/$f'
			curl -fsSL -o '$f.sha256' '$LAB_DL/$LAB_ROS/$f.sha256'
			mv '$f.part' '$f'"
	done
	tool "set -e; cd downloads/$LAB_ROS; sha256sum -c '$img_zip.sha256' '$pkg_zip.sha256'" >&2 ||
		die "checksum mismatch: delete $DL and fetch again"
}

# disk turns MikroTik's raw image into base.qcow2, grown to LAB_DISK_SIZE, and
# pulls container-<v>.npk out of the extra-packages archive.
cmd_disk() {
	cmd_fetch
	mkdir -p "$VM"
	if [ ! -f "$VM/base.qcow2" ]; then
		say "converting $img_zip to base.qcow2 ($LAB_DISK_SIZE)"
		tool "set -e; tmp=\$(mktemp -d)
			unzip -q -o 'downloads/$LAB_ROS/$img_zip' -d \$tmp
			qemu-img convert -O qcow2 \$tmp/*.img 'vm/$LAB_ARCH-$LAB_ROS/base.qcow2'
			qemu-img resize -q 'vm/$LAB_ARCH-$LAB_ROS/base.qcow2' '$LAB_DISK_SIZE'
			chmod a-w 'vm/$LAB_ARCH-$LAB_ROS/base.qcow2'
			rm -rf \$tmp"
	fi
	if [ ! -f "$VM/container-$LAB_ROS.npk" ]; then
		tool "set -e; unzip -q -o -j 'downloads/$LAB_ROS/$pkg_zip' 'container-$LAB_ROS*.npk' -d 'vm/$LAB_ARCH-$LAB_ROS'
			cd 'vm/$LAB_ARCH-$LAB_ROS'; for f in container-*.npk; do [ \"\$f\" = container-$LAB_ROS.npk ] || mv \"\$f\" container-$LAB_ROS.npk; done"
		[ -f "$VM/container-$LAB_ROS.npk" ] || die "no container package in $pkg_zip"
	fi
}

# overlay makes $2 a copy-on-write layer over $1, by a relative backing path so
# the chain reads the same inside the container and out.
overlay() {
	tool "set -e; cd 'vm/$LAB_ARCH-$LAB_ROS'; rm -f '$2'; qemu-img create -q -f qcow2 -b '$1' -F qcow2 '$2'"
}

# ─── The machine ─────────────────────────────────────────────────────────────

state() { docker inspect -f '{{.State.Status}}' "$NAME" 2>/dev/null || echo absent; }

# start runs the container on the given disk, or powers an existing one back on.
start() {
	local disk=$1
	case "$(state)" in
	running) return 0 ;;
	exited | created)
		docker start "$NAME" >/dev/null
		return 0
		;;
	esac
	local kvm=()
	[ -e /dev/kvm ] && kvm=(--device /dev/kvm)
	docker run -d --name "$NAME" --hostname "$NAME" \
		--label org.opencontainers.image.source=https://github.com/jmrplens/mikroscope \
		--label mikroscope.lab.arch="$LAB_ARCH" --label mikroscope.lab.ros="$LAB_ROS" \
		--cap-add NET_ADMIN --device /dev/net/tun "${kvm[@]}" \
		-e LAB_ARCH="$LAB_ARCH" -e LAB_MEM="$LAB_MEM" -e LAB_CPUS="$LAB_CPUS" \
		-e LAB_AGENT_ROUTES="$LAB_AGENT_ROUTES" -e LAB_AGENT_TARGET="$LAB_AGENT_TARGET" \
		-e LAB_DISK="/cache/vm/$LAB_ARCH-$LAB_ROS/$disk" \
		-e LAB_CONSOLE_LOG="/cache/vm/$LAB_ARCH-$LAB_ROS/console.log" \
		-v "$CACHE:/cache" -v "$LAB_DIR/vm:/lab/vm:ro" -v "$SSHD:/lab/ssh:ro" \
		-p "127.0.0.1:$P_SSH:22" -p "127.0.0.1:$P_HTTP:80" \
		-p "127.0.0.1:$P_API:8728" -p "127.0.0.1:$P_AGENT:9123" \
		"$LAB_IMAGE" >/dev/null
}

# inlab runs a command inside the lab container, in its network namespace.
inlab() { docker exec -i "$NAME" "$@"; }

# ros runs one RouterOS command over ssh, from the LAN side.
ros() { inlab ssh lab "$1"; }

# wait_ssh waits until the router answers on ssh by the given alias.
wait_ssh() {
	local alias=${1:-lab} limit=${2:-300} i=0
	while ! inlab ssh -o ConnectTimeout=2 "$alias" ':put ok' >/dev/null 2>&1; do
		[ "$(state)" = running ] || die "the lab container stopped: docker logs $NAME; tail $VM/console.log"
		i=$((i + 3))
		[ $i -lt "$limit" ] || die "no ssh from the router after ${limit}s"
		sleep 1
	done
}

# wait_down waits for the container to stop, which is the guest powering off.
wait_down() {
	local limit=${1:-120} i=0
	while [ "$(state)" = running ]; do
		i=$((i + 1))
		[ $i -lt "$limit" ] || return 1
		sleep 1
	done
}

monitor() { inlab bash -c "printf '%s\n' '$1' | socat - UNIX-CONNECT:/run/lab/monitor.sock" >/dev/null 2>&1 || true; }

# ─── Provisioning ────────────────────────────────────────────────────────────

# provision builds clean.qcow2: a fresh CHR with the lab's access (password,
# key, LAN address on ether2), the container package installed and
# device-mode container=yes confirmed by a cold reboot. Nothing else is
# configured: interface lists, address lists and firewall stay as CHR ships
# them, so what a test needs beyond that it sets up itself — or finds out, as a
# user would, from `mikroscope doctor`.
cmd_provision() {
	if [ -f "$VM/clean.qcow2" ] && [ "${FORCE:-0}" != 1 ]; then
		say "clean snapshot exists ($VM/clean.qcow2); FORCE=1 to rebuild it"
		return 0
	fi
	cmd_image
	load_env
	ensure_key
	cmd_disk
	[ "$(state)" = absent ] || docker rm -f "$NAME" >/dev/null
	overlay base.qcow2 provision.qcow2
	: >"$VM/console.log"

	say "first boot of CHR $LAB_ROS ($LAB_ARCH)"
	start provision.qcow2
	local i=0
	while ! inlab sshpass -p '' ssh -o ConnectTimeout=3 -o PubkeyAuthentication=no lab-wan ':put ok' >/dev/null 2>&1; do
		[ "$(state)" = running ] || die "the lab container stopped during first boot: docker logs $NAME"
		i=$((i + 3))
		[ $i -lt 600 ] || die "no ssh from the router on ether1 after 600s"
		sleep 3
	done
	say "router up; ssh as admin with CHR's empty password over ether1"

	local pub
	pub=$(cat "$SSHD/id_ed25519.pub")
	# One connect: the LAN address, the identity, the key, then the password,
	# which ends the empty-password login this session is using.
	inlab sshpass -p '' ssh -o PubkeyAuthentication=no lab-wan \
		"/system/identity/set name=mikroscope-lab-$short; /ip/address/add address=192.168.88.1/24 interface=ether2 comment=\"lab LAN\"; /user/ssh-keys/add user=admin key=\"$pub\"; /user/set [find name=admin] password=\"$LAB_ADMIN_PASSWORD\"" >/dev/null
	wait_ssh lab 60
	say "ssh by key over ether2 (LAN) works; password set"

	say "uploading container-$LAB_ROS.npk"
	inlab scp -q "/cache/vm/$LAB_ARCH-$LAB_ROS/container-$LAB_ROS.npk" "lab:container-$LAB_ROS.npk"
	ros '/system/reboot' >/dev/null 2>&1 || true
	sleep 5
	wait_ssh lab 300
	local pkg
	pkg=$(ros ':put [:len [/system/package/find name="container" disabled=no]]' | tr -d '\r')
	[ "$pkg" = 1 ] || die "the container package is not installed after the reboot (found=$pkg)"
	say "container package installed"

	cmd_device_mode
	say "device-mode container=yes confirmed"

	say "shutting the router down for the snapshot"
	ros '/system/shutdown' >/dev/null 2>&1 || true
	wait_down 120 || die "the router did not power off within 120s"
	docker rm "$NAME" >/dev/null
	mv -f "$VM/provision.qcow2" "$VM/clean.qcow2"
	chmod a-w "$VM/clean.qcow2"
	overlay clean.qcow2 run.qcow2
	say "clean snapshot: $VM/clean.qcow2 (over base.qcow2); run.qcow2 is the live layer"
}

# device_mode asks for container=yes and confirms it the way MikroTik
# documents for a device with no button to press: a cold reboot inside the
# activation window (activation-timeout, 5 min by default; MikroTik's
# Device-mode page: "perform a 'cold reboot' - that is, unplug the power"). The
# update command holds its console while it waits — on CHR 7.24.4 it prints
# `update: turn off power in 5m to activate changes`, not the documented
# `please activate by turning power off or pressing reset or mode button` —
# and the power is pulled under it (QEMU quits) and put back (docker start).
# MikroTik counts update attempts and allows three before a power cycle resets
# the counter; each provision is a fresh disk, so it starts at zero.
cmd_device_mode() {
	local now
	now=$(ros ':put [/system/device-mode/get container]' | tr -d '\r')
	if [ "$now" = yes ] || [ "$now" = true ]; then
		say "device-mode container is already yes"
		return 0
	fi
	inlab bash -c 'ssh lab "/system/device-mode/update container=yes" >/run/lab/device-mode.out 2>&1 &'
	local i=0
	until inlab grep -qi 'activate\|power' /run/lab/device-mode.out 2>/dev/null; do
		i=$((i + 1))
		[ $i -lt 30 ] || {
			inlab cat /run/lab/device-mode.out >&2 || true
			die "device-mode update never asked for its confirmation"
		}
		sleep 1
	done
	say "RouterOS: $(inlab cat /run/lab/device-mode.out | tr -d '\r' | grep -i -m1 'activate\|power' | sed 's/ *--.*//')"
	say "pulling the power (QEMU quit) and putting it back"
	monitor quit
	wait_down 30 || die "QEMU did not quit"
	docker start "$NAME" >/dev/null
	sleep 5
	wait_ssh lab 300
	# MikroTik writes that a confirmed change reboots the device by itself. On
	# CHR 7.24.4 (2026-09-26) the boot after the power cut was the only one:
	# the console showed no further boot, and the first ssh after it already
	# read container=true.
	now=$(ros ':put [/system/device-mode/get container]' | tr -d '\r')
	[ "$now" = yes ] || [ "$now" = true ] || die "device-mode container=$now after the power cycle"
}

# ─── Verbs ───────────────────────────────────────────────────────────────────

cmd_up() {
	ensure_image
	load_env
	ensure_key
	[ -f "$VM/clean.qcow2" ] || cmd_provision
	[ -f "$VM/run.qcow2" ] || overlay clean.qcow2 run.qcow2
	if [ "$(state)" != running ]; then
		say "starting $NAME"
		start run.qcow2
	fi
	wait_ssh lab 300
	say "up: ssh 127.0.0.1:$P_SSH, WebFig http://127.0.0.1:$P_HTTP, API 127.0.0.1:$P_API, agent 127.0.0.1:$P_AGENT (-> $LAB_AGENT_TARGET)"
}

cmd_down() {
	if [ "$(state)" = running ]; then
		say "shutting the router down"
		ros '/system/shutdown' >/dev/null 2>&1 || monitor system_powerdown
		wait_down 90 || {
			say "no power-off after 90s: pulling the power"
			docker stop -t 5 "$NAME" >/dev/null
		}
	fi
	[ "$(state)" = absent ] || docker rm "$NAME" >/dev/null
	say "down (the disk keeps its state; reset discards it)"
}

cmd_reset() {
	[ -f "$VM/clean.qcow2" ] || die "no clean snapshot yet: run lab.sh up (or provision) first"
	[ "$(state)" = absent ] || docker rm -f "$NAME" >/dev/null
	overlay clean.qcow2 run.qcow2
	say "run.qcow2 reset to the clean snapshot"
	cmd_up
}

cmd_power_cycle() {
	[ "$(state)" = running ] || die "$NAME is not running"
	monitor quit
	wait_down 30 || die "QEMU did not quit"
	docker start "$NAME" >/dev/null
	wait_ssh lab 300
	say "power-cycled"
}

cmd_status() {
	local st
	st=$(state)
	echo "container: $NAME ($st), image $LAB_IMAGE, RouterOS $LAB_ROS $LAB_ARCH"
	local disks="" d
	for d in "$VM"/*.qcow2; do [ -f "$d" ] && disks+="$(basename "$d") "; done
	echo "disks:     ${disks:-none}"
	[ "$st" = running ] || return 0
	echo "host:      ssh 127.0.0.1:$P_SSH  WebFig http://127.0.0.1:$P_HTTP  API 127.0.0.1:$P_API  agent 127.0.0.1:$P_AGENT"
	# One connect for every reading, as on a real router.
	ros ':put ("router:    " . [/system/identity/get name] . ", " . [/system/resource/get board-name] . ", RouterOS " . [/system/resource/get version] . ", " . [/system/resource/get architecture-name] . ", up " . [/system/resource/get uptime]); :put ("memory:    free " . ([/system/resource/get free-memory] / 1048576) . " MiB of " . ([/system/resource/get total-memory] / 1048576) . "; disk free " . ([/system/resource/get free-hdd-space] / 1048576) . " MiB of " . ([/system/resource/get total-hdd-space] / 1048576)); :put ("container: package " . [:len [/system/package/find name="container" disabled=no]] . ", device-mode container=" . [/system/device-mode/get container] . ", containers " . [:len [/container/find]] . ", veths " . [:len [/interface/veth/find]]); :put ("licence:   " . [/system/license/get level])' | tr -d '\r'
}

# residue counts, in one connect, everything an install can leave behind:
# what `mikroscope uninstall` verifies and what it does not look at. Compare it
# with a reading taken before the install.
cmd_residue() {
	# shellcheck disable=SC2016 # $f is RouterOS's variable, not the shell's
	ros ':put ("containers " . [:len [/container/find]] . ", envs " . [:len [/container/envs/find]] . ", mounts " . [:len [/container/mounts/find]] . ", veths " . [:len [/interface/veth/find]] . ", ip-addresses " . [:len [/ip/address/find]] . ", list-members " . [:len [/interface/list/member/find]] . ", filter " . [:len [/ip/firewall/filter/find]] . ", nat " . [:len [/ip/firewall/nat/find]] . ", raw " . [:len [/ip/firewall/raw/find]] . ", address-lists " . [:len [/ip/firewall/address-list/find]] . ", disks " . [:len [/disk/find]]); :foreach f in=[/file/find] do={ :put ("file " . [/file/get $f name] . " (" . [/file/get $f type] . ")") }' | tr -d '\r'
}

cmd_ssh() {
	if [ $# -eq 0 ]; then
		docker exec -it "$NAME" ssh lab
	else
		ros "$*"
	fi
}

# cli runs the mikroscope CLI from the lab's LAN side: a throwaway container in
# the lab's network namespace, so `--router lab` is the lab router and the
# agent's veth address is routed to it. Nothing from the host's environment
# reaches it — no MIKROSCOPE_* variable set for a real router can leak in —
# except MIKROSCOPE_ROUTER=lab. The current directory is mounted at /work, so
# relative --out and --agent-tar paths work.
cmd_cli() {
	local bin=${MIKROSCOPE_BIN:-$(command -v mikroscope || true)}
	[ -n "$bin" ] && [ -x "$bin" ] || die "no mikroscope binary: put one on PATH or set MIKROSCOPE_BIN"
	bin=$(cd "$(dirname "$bin")" && pwd)/$(basename "$bin")
	[ "$(state)" = running ] || die "$NAME is not running: lab.sh up"
	local tty=()
	[ -t 0 ] && [ -t 1 ] && tty=(-t)
	docker run --rm -i "${tty[@]}" --network "container:$NAME" \
		-v "$bin:/usr/local/bin/mikroscope:ro" -v "$LAB_DIR/vm:/lab/vm:ro" -v "$SSHD:/lab/ssh:ro" \
		-v "$PWD:/work" -w /work -e MIKROSCOPE_ROUTER=lab \
		--entrypoint /lab/vm/cli.sh "$LAB_IMAGE" mikroscope "$@"
}

# put uploads a local file to the router (default: its own name).
cmd_put() {
	local src=$1 dst=${2:-$(basename "$1")}
	[ -f "$src" ] || die "no such file: $src"
	docker cp "$src" "$NAME:/tmp/lab-upload" >/dev/null
	inlab scp -q /tmp/lab-upload "lab:$dst"
	inlab rm -f /tmp/lab-upload
	say "uploaded $src as $dst"
}

# import uploads a RouterOS script, runs it with /import and removes it, so
# the router keeps what the script did and not the file.
cmd_import() {
	local src=$1 name
	name=lab-$(basename "$src")
	cmd_put "$src" "$name"
	ros "/import file-name=$name; /file/remove [find name=\"$name\"]"
}

cmd_console() {
	echo "serial console of $NAME; Ctrl-] then Enter... leaves (socat: Ctrl-C)" >&2
	docker exec -it "$NAME" socat -,raw,echo=0,escape=0x1d UNIX-CONNECT:/run/lab/console.sock
}

cmd_env() {
	echo "credentials: $ENV_FILE (LAB_ADMIN_USER, LAB_ADMIN_PASSWORD, LAB_AGENT_TOKEN)"
	echo "ssh key:     $SSHD/id_ed25519"
	echo "from the host: ssh -i $SSHD/id_ed25519 -p $P_SSH -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null admin@127.0.0.1"
}

verb=${1:-status}
[ $# -gt 0 ] && shift
case "$verb" in
up) cmd_up ;;
down) cmd_down ;;
reset) cmd_reset ;;
status) cmd_status ;;
residue) cmd_residue ;;
provision) cmd_provision ;;
device-mode) cmd_device_mode ;;
fetch) cmd_fetch ;;
disk) cmd_disk ;;
image) cmd_image ;;
ssh) cmd_ssh "$@" ;;
cli) cmd_cli "$@" ;;
put) cmd_put "$@" ;;
import) cmd_import "$@" ;;
console) cmd_console ;;
power-cycle) cmd_power_cycle ;;
env) cmd_env ;;
*)
	awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); print; next } NR > 1 { exit }' "${BASH_SOURCE[0]}"
	exit 2
	;;
esac
