package e2e

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

// The dashboards are generated by the collector binary and validated here
// without a Grafana: `dashboards import` and `dashboards check` need one and
// are not part of this suite. What can be checked without it is everything
// that makes a dashboard wrong before it is ever opened — a panel with no
// target, a row that does not carry its children, a query naming a
// measurement no sink writes — and the last of those is checked against the
// measurements a real forward run actually put on the wire, not against a
// list kept by hand.

// dashboard is as much of the JSON as this suite reads.
type dashboard struct {
	UID           string  `json:"uid"`
	Title         string  `json:"title"`
	Description   string  `json:"description"`
	SchemaVersion int     `json:"schemaVersion"`
	Panels        []dpane `json:"panels"`
	Templating    struct {
		List []any `json:"list"`
	} `json:"templating"`
}

type dpane struct {
	ID          int    `json:"id"`
	Type        string `json:"type"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Collapsed   bool   `json:"collapsed"`
	GridPos     struct {
		X, Y, W, H int
	} `json:"gridPos"`
	Targets []struct {
		RefID  string `json:"refId"`
		RawSQL string `json:"rawSql"`
		Expr   string `json:"expr"`
	} `json:"targets"`
	Panels []dpane `json:"panels"`
}

// generateDashboards runs `dashboards gen` and returns the two documents.
func generateDashboards(t *testing.T) map[string]dashboard {
	t.Helper()
	dir := t.TempDir()
	p := startCollector(t, childEnv(), "dashboards", "gen", "--out", dir)
	p.Wait(t, 60*time.Second)

	out := map[string]dashboard{}
	for _, store := range []string{"influxdb", "prometheus"} {
		path := filepath.Join(dir, "mikroscope-"+store+".json")
		raw, err := os.ReadFile(path) // #nosec G304 -- the suite's own temp dir
		if err != nil {
			t.Fatalf("dashboards gen wrote no %s file: %v\n%s", store, err, p.Output())
		}
		var d dashboard
		if jsonErr := json.Unmarshal(raw, &d); jsonErr != nil {
			t.Fatalf("the %s dashboard is not valid JSON: %v", store, jsonErr)
		}
		out[store] = d
	}
	return out
}

func TestDashboardsGenProducesWellFormedPanels(t *testing.T) {
	t.Parallel()
	for store, d := range generateDashboards(t) {
		checkDashboardIdentity(t, store, d)
		checkPanelsWellFormed(t, store, d.Panels)
	}
}

// checkDashboardIdentity checks the uid, title, description and schema
// version. The uid is fixed, because it is what `dashboards import` updates
// in place and what a Grafana provisioning file references. A uid that
// changed between releases would leave a second copy of the dashboard behind
// on every import.
func checkDashboardIdentity(t *testing.T, store string, d dashboard) {
	t.Helper()
	if want := "mikroscope-" + store; d.UID != want {
		t.Errorf("%s: uid = %q, want %q", store, d.UID, want)
	}
	if d.Title == "" || d.Description == "" || d.SchemaVersion == 0 {
		t.Errorf("%s: title %q, schemaVersion %d, description %d bytes",
			store, d.Title, d.SchemaVersion, len(d.Description))
	}
}

// checkPanelsWellFormed checks every panel, a collapsed row's children
// included: a title, an id no other panel uses, and the geometry and targets
// its type requires. It also checks there are enough panels to be a
// dashboard.
func checkPanelsWellFormed(t *testing.T, store string, ps []dpane) {
	t.Helper()
	ids := map[int]bool{}
	var panels int
	for _, p := range flatten(ps) {
		panels++
		if p.Title == "" {
			t.Errorf("%s: panel %d has no title", store, p.ID)
		}
		if ids[p.ID] {
			t.Errorf("%s: panel id %d is used twice; Grafana keys its layout on the id", store, p.ID)
		}
		ids[p.ID] = true
		if p.Type == "row" {
			if p.GridPos.H != 1 || p.GridPos.W != 24 {
				t.Errorf("%s: row %q is %dx%d, not the full-width single line Grafana recognizes",
					store, p.Title, p.GridPos.W, p.GridPos.H)
			}
			continue
		}
		checkQueryPanel(t, store, p)
	}
	if panels < 20 {
		t.Errorf("%s: the dashboard has %d panels", store, panels)
	}
}

// checkQueryPanel checks a panel that is not a row: it has at least one
// target, every target has a refId and a query, and it has a size.
func checkQueryPanel(t *testing.T, store string, p dpane) {
	t.Helper()
	// A panel with no target queries nothing and paints "No data" for ever.
	if len(p.Targets) == 0 {
		t.Errorf("%s: panel %q has no target", store, p.Title)
		return
	}
	for _, tg := range p.Targets {
		q := tg.RawSQL + tg.Expr
		if strings.TrimSpace(q) == "" {
			t.Errorf("%s: panel %q has target %s with an empty query", store, p.Title, tg.RefID)
		}
		if tg.RefID == "" {
			t.Errorf("%s: panel %q has a target with no refId", store, p.Title)
		}
	}
	if p.GridPos.W < 1 || p.GridPos.W > 24 || p.GridPos.H < 1 {
		t.Errorf("%s: panel %q is %dx%d", store, p.Title, p.GridPos.W, p.GridPos.H)
	}
}

// TestDashboardSectionsAreCollapsedExceptTheFirst pins the sectioning: an
// Overview open and every other section closed, in reading order. A
// collapsed row's children live inside the row object, which is the only
// place Grafana reads them from — and the only way to stop a panel whose
// measurement is absent from painting a datasource-error badge, because the
// query of a collapsed row's child never runs.
func TestDashboardSectionsAreCollapsedExceptTheFirst(t *testing.T) {
	t.Parallel()
	for store, d := range generateDashboards(t) {
		checkSectionRows(t, store, d.Panels)
		// The open section's panels sit at the top level, and the collapsed
		// ones' do not: a child left outside a collapsed row is rendered and
		// queried whatever the row says.
		if n := topLevelPanelsUnderCollapsedRows(d.Panels); n > 0 {
			t.Errorf("%s: %d panels sit at the top level under a collapsed row, so they render and query anyway",
				store, n)
		}
	}
}

// checkSectionRows checks the top-level rows: at least five, the first open,
// and every other one collapsed with its children inside it.
func checkSectionRows(t *testing.T, store string, ps []dpane) {
	t.Helper()
	var rows []dpane
	for _, p := range ps {
		if p.Type == "row" {
			rows = append(rows, p)
		}
	}
	if len(rows) < 5 {
		t.Fatalf("%s: %d rows; the dashboard is not sectioned", store, len(rows))
	}
	if rows[0].Collapsed {
		t.Errorf("%s: the first section %q is collapsed, so the dashboard opens on nothing", store, rows[0].Title)
	}
	for _, r := range rows[1:] {
		if !r.Collapsed {
			t.Errorf("%s: section %q is open; every section but the first ships closed", store, r.Title)
		}
		if len(r.Panels) == 0 {
			t.Errorf("%s: collapsed section %q carries no panels, so expanding it shows nothing", store, r.Title)
		}
	}
}

// topLevelPanelsUnderCollapsedRows counts the top-level panels that follow a
// collapsed row rather than living inside it.
func topLevelPanelsUnderCollapsedRows(ps []dpane) int {
	var n int
	underCollapsed := false
	for _, p := range ps {
		if p.Type == "row" {
			underCollapsed = p.Collapsed
			continue
		}
		if underCollapsed {
			n++
		}
	}
	return n
}

// TestDashboardTitlesDoNotAssumeTheDevice: a title says what the panel
// shows. Anyone who deploys this project has a different router — a
// different core count, a different amount of RAM, different interface
// names, maybe no SFP port at all — so a measurement of the reference device
// belongs in the description, attributed, and never in a title.
func TestDashboardTitlesDoNotAssumeTheDevice(t *testing.T) {
	t.Parallel()
	// Names and figures that are properties of the reference RB5009 rather
	// than of the metric. The list is the vocabulary a title must not use;
	// a description may, as long as it says which device and when.
	deviceSpecific := regexp.MustCompile(`(?i)\b(rb5009|hex\s?s|switch0|ether\d|sfp\+?\d*|mvpp2|1 GiB|512 MB|four cores|4 cores|the four\b|cortex-a72|arm-pmu)\b`)
	for store, d := range generateDashboards(t) {
		for _, p := range flatten(d.Panels) {
			if m := deviceSpecific.FindString(p.Title); m != "" {
				t.Errorf("%s: title %q names %q, which is a property of one board, not of the metric",
					store, p.Title, m)
			}
		}
	}
}

// TestDashboardQueriesDoNotHardcodeDimensions: no query may pin a core
// count, an interface name, a NIC driver or a thermal zone. Dimensions come
// from the data — cores from GROUP BY core, the NIC's interrupt lines from
// "the lines whose rate is highest" — because the reader's board has
// different ones.
func TestDashboardQueriesDoNotHardcodeDimensions(t *testing.T) {
	t.Parallel()
	forbidden := regexp.MustCompile(`(?i)(switch0|mvpp2|ether\d|sfp-?sfpplus\d*|cpu-thermal|'?nf_conntrack'?\s*=|core\s*(=|IN)\s*\(?\s*'?[0-3]'?\s*[,)]|999956|1048576\b)`)
	for store, d := range generateDashboards(t) {
		for _, p := range flatten(d.Panels) {
			for _, tg := range p.Targets {
				q := tg.RawSQL + tg.Expr
				if m := forbidden.FindString(q); m != "" {
					t.Errorf("%s: panel %q target %s pins %q, a dimension of one board:\n%s",
						store, p.Title, tg.RefID, m, q)
				}
			}
		}
	}
}

// influxFrom finds the measurements a SQL target reads. Only identifiers
// under the mikroscope_ prefix count: a query's own subquery aliases (b, m,
// ranked) are FROM targets too and are not measurements.
var influxFrom = regexp.MustCompile(`(?i)\b(?:FROM|JOIN)\s+(mikroscope_[a-z0-9_]+)`)

// promMetric finds the metric names a PromQL target reads.
var promMetric = regexp.MustCompile(`\bmikroscope_[a-z0-9_]+`)

// TestNoDashboardPanelAsksForSomethingNoSinkWrites is the cross-check the
// panel titles cannot do for themselves: every measurement an InfluxDB panel
// reads has to be a measurement the InfluxDB sink writes, and every metric a
// Prometheus panel reads has to be one the Prometheus sink serves. Both sets
// come from a real forward run in this test rather than from a list, so a
// sink that stops emitting a family fails here instead of leaving a panel
// that says "No data" on someone's wall.
func TestNoDashboardPanelAsksForSomethingNoSinkWrites(t *testing.T) {
	t.Parallel()
	a := newFakeAgent(t, "")
	influx := newCapture(t, nil)
	promAddr := freeAddr(t)

	p := startForward(t, a, 8*time.Second,
		"--influx", influx.URL()+"/api/v3/write_lp?db=mikroscope",
		"--prom", promAddr)
	exposition := awaitEveryFamily(t, promAddr, p)
	p.Wait(t, 120*time.Second)

	written := measurementsOf(parseLineProtocol(t, influx.Body()))
	served := servedMetrics(t, a, exposition, p)
	if len(written) < 10 || len(served) < 20 {
		t.Fatalf("the run produced %d measurements and %d metrics, too few to cross-check against",
			len(written), len(served))
	}

	dashes := generateDashboards(t)
	checkInfluxPanelsReadWrittenMeasurements(t, dashes["influxdb"].Panels, written)
	checkPromPanelsReadServedMetrics(t, dashes["prometheus"].Panels, served)
}

// awaitEveryFamily waits for the collector's exposition to carry the LAST
// family to appear, not the first, and returns it. The exporter grows its
// family set as samples arrive, and the fake agent's canned stream carries
// the privileged sources (slab census) and the event records (kernel log) in
// different samples: scraping on the first marker alone caught an exposition
// without kmsg and failed the four kernel-log panels for a race rather than
// for a gap (2026-09-13).
//
// One marker per shape that brings a family no other shape does. The floored
// shape (buddyinfo and MTD) comes one tick after the kernel-log shape, and
// without its own marker a scrape landing between the two failed every buddy
// and MTD panel: 5 runs out of 5 with every core busy, 0 out of 6 idle
// (2026-09-15). A shape added to fakeagent.Shapes with a family of its own
// needs its marker here for the same reason.
func awaitEveryFamily(t *testing.T, promAddr string, p *proc) string {
	t.Helper()
	markers := []string{
		`mikroscope_slab_active_objects{`, // privileged sources
		`mikroscope_kmsg_records_total{`,  // the kernel-log shape
		`mikroscope_buddy_free_blocks{`,   // the floored shape
		`mikroscope_mtd_blocks{`,          // the floored shape
	}
	var exposition string
	if !waitFor(60*time.Second, func() bool {
		b, up := scrape(t, promAddr)
		if !up || !containsAll(b, markers) {
			return false
		}
		exposition = b
		return true
	}) {
		t.Fatalf("the Prometheus sink never served every family:\n%s", p.Output())
	}
	return exposition
}

// containsAll reports whether s contains every one of subs.
func containsAll(s string, subs []string) bool {
	for _, sub := range subs {
		if !strings.Contains(s, sub) {
			return false
		}
	}
	return true
}

// servedMetrics is the set of metric names the Prometheus dashboard's one
// scrape job serves: the collector's. Since 1.0.5 there is no second job —
// the agent serves no exposition at all, and what only a sampler can count
// (its tick timing, slipped ticks, the trigger and capture counters) reaches
// the collector as data over /sampler and is rendered here with everything
// else. A family missing from this set is missing from the deployment.
func servedMetrics(t *testing.T, _ *agentFixture, exposition string, _ *proc) map[string]bool {
	t.Helper()
	samples, _ := parseExposition(t, exposition)
	served := map[string]bool{}
	for _, s := range samples {
		served[s.Name] = true
	}
	return served
}

// checkInfluxPanelsReadWrittenMeasurements checks that every measurement an
// InfluxDB panel reads is one the run wrote, or one only the API tier can
// produce.
func checkInfluxPanelsReadWrittenMeasurements(t *testing.T, ps []dpane, written map[string]int) {
	t.Helper()
	for _, p := range flatten(ps) {
		for _, tg := range p.Targets {
			for _, m := range influxFrom.FindAllStringSubmatch(tg.RawSQL, -1) {
				name := strings.ToLower(m[1])
				if written[name] > 0 || isAPITier(name) || isAPIDerived(name) {
					continue
				}
				t.Errorf("InfluxDB panel %q reads %s, which no sink writes; what the run wrote: %v",
					p.Title, name, sortedKeys(written))
			}
		}
	}
}

// checkPromPanelsReadServedMetrics checks that every metric a Prometheus
// panel reads is one the run served, a child series of a served histogram,
// or one only the API tier can produce.
func checkPromPanelsReadServedMetrics(t *testing.T, ps []dpane, served map[string]bool) {
	t.Helper()
	for _, p := range flatten(ps) {
		for _, tg := range p.Targets {
			for _, name := range promMetric.FindAllString(tg.Expr, -1) {
				if served[name] || isAPITier(name) || isAPIDerived(name) || isHistogramChild(name, served) {
					continue
				}
				t.Errorf("Prometheus panel %q reads %s, which the exporter does not serve; what it served: %v",
					p.Title, name, sortedKeys(served))
			}
		}
	}
}

// isAPITier reports whether a name belongs to the RouterOS API tier. The API
// tier needs a router, so this suite cannot make it emit anything and cannot
// judge its measurements; `dashboards check` against a live Grafana is what
// covers those.
func isAPITier(name string) bool {
	return strings.HasPrefix(name, "mikroscope_api_")
}

// isAPIDerived is the same exemption one stage further down, and for exactly
// the same reason: these two families are the derive stage's output over
// API-tier INPUT, and the input is per-interface byte counters. Those are
// namespaced — a container, privileged or not, does not share the router's
// network namespace, which is why net/dev is in
// every agent's Namespaced list — so no kernel agent, real or fake, can
// produce the rows they are computed from (derive.Stage.API, fed only from
// apitier.Sample.IfaceCounters). They are named mikroscope_derived_* rather
// than mikroscope_api_*, which is why the prefix rule above does not reach
// them; the tier they depend on is the same one.
func isAPIDerived(name string) bool {
	return name == "mikroscope_derived_iface" || name == "mikroscope_derived_fastpath_share"
}

// isHistogramChild reports whether name is a bucket, sum or count of a
// histogram the exporter serves, which is a series a dashboard may read even
// though the base name is what carries the TYPE line.
func isHistogramChild(name string, served map[string]bool) bool {
	for _, suffix := range []string{"_bucket", "_sum", "_count"} {
		if base, ok := strings.CutSuffix(name, suffix); ok {
			if served[base] || served[base+"_bucket"] || served[base+"_count"] {
				return true
			}
		}
	}
	return false
}

// flatten walks a dashboard's panels, a collapsed row's children included.
func flatten(ps []dpane) []dpane {
	out := make([]dpane, 0, len(ps))
	for _, p := range ps {
		out = append(out, p)
		out = append(out, flatten(p.Panels)...)
	}
	return out
}

// TestDashboardOpensOnTheEverydayQuestions pins the READING ORDER, which is a
// design decision a later edit can undo silently (owner, 2026-09-13:
// "normalmente lo primero que se quiere ver es cpu, RAM, conexiones y cosas
// así, y en otras secciones el resto de datos").
//
// It asserts the shape of the argument rather than the exact list: the first
// row is open and is the Overview, and the four rows after it are the four
// everyday questions — CPU, memory, connections, interface traffic — in that
// order. Everything below is free to be reordered. Sections that ship no row
// on a device (Pressure stall, Block devices) are skipped rather than
// asserted, because whether they appear is a property of the store.
func TestDashboardOpensOnTheEverydayQuestions(t *testing.T) {
	t.Parallel()
	want := []string{"CPU and scheduler", "Memory and load", "Connections", "Interface traffic"}
	for store, d := range generateDashboards(t) {
		var rows []string
		for _, p := range d.Panels {
			if p.Type == "row" {
				rows = append(rows, p.Title)
			}
		}
		if len(rows) == 0 || rows[0] != "Overview" {
			t.Fatalf("%s: first row is %v, want Overview", store, rows)
		}
		if len(rows) <= len(want) {
			t.Fatalf("%s: only %d rows", store, len(rows))
		}
		for i, w := range want {
			if rows[i+1] != w {
				t.Errorf("%s: row %d is %q, want %q — the everyday questions lead, in order: %v",
					store, i+1, rows[i+1], w, want)
			}
		}
	}
}
